syn on
se mouse=a ai sta et
se ts=2 sts=2 sw=2 st=2 ls=2
ino ( ()<LEFT>
ino [ []<LEFT>
ino {<CR> {<CR>;<BS><CR>}<UP><TAB>

no <F9> :!g++ -O2 -std=c++17 -lm % -fsanitize=undefined -Wall -Wextra -Wshadow -Wno-unused-result<CR>
no <F5> :!./a.out<CR>
